// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 5
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){


var __c;(function(){(function(a){__c=a;__c.a="c";__c.b=["google"];__c.c=!0})(function(a){return a["29"]})})();

var __awct;(function(){var a=!1,b=[],c=function(a){var b=q("google_trackConversion"),c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},d=function(){for(;0<b.length;)c(b.shift())},e=function(){return function(){d();a=!1;var b=Ya["//www.googleadservices.com/pagead/conversion_async.js"];b&&3==b.status&&(Ya["//www.googleadservices.com/pagead/conversion_async.js"]=void 0)}},f=function(){return function(){d();b={push:c};}};
(function(a){__awct=a;__awct.a="awct";__awct.b=["google"];__awct.c=!0})(function(c){var d={google_conversion_domain:"",google_conversion_id:c["26"],google_conversion_label:c["27"],google_conversion_value:c[""]||0,google_remarketing_only:!1,onload_callback:c["30"],gtm_onFailure:c["31"],google_gtm:qa()};c[""]&&(d.google_conversion_currency=c[""]);
c[""]&&(d.google_conversion_order_id=c[""]);c[""]&&(d.google_read_ga_cookie_opt_in=!0);c[""]?c[""]&&(d.google_gcl_cookie_prefix=c[""]):d.google_read_gcl_cookie_opt_out=!0;b.push(d);a||(a=!0,Ka("//www.googleadservices.com/pagead/conversion_async.js",f(),e()))})})();





var Ib=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Jb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Kb=function(a){if(null==a)return String(a);var b=Jb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Lb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Fa=function(a){if(!a||"object"!=Kb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Lb(a,"constructor")&&!Lb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Lb(a,b)},Da=function(a,b){var c=b||("array"==Kb(a)?[]:{}),d;for(d in a)if(Lb(a,d)){var e=a[d];"array"==Kb(e)?("array"!=Kb(c[d])&&(c[d]=[]),c[d]=Da(e,c[d])):Fa(e)?(Fa(c[d])||(c[d]={}),c[d]=Da(e,c[d])):c[d]=e}return c};var Ba={},ob=null,Mb=Math.random();Ba.f="GTM-MVMGKF";var Nb=null,wa=null,Ra=!1,Ob="//www.googletagmanager.com/a?id="+Ba.f+"&cv=5",Pb={},Qb={},Sa={};var Ua,Va,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,
We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf,Mf,Nf;
(function(){var a=function(a){return{toString:function(){return a}}};Rb=a("");Sb=a("0");Tb="";Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("2");cc=a("3");dc=a("");ec=a("");fc=a("");
gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");
uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("");Ac=a("4");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");
Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("5");Tc=a("");Uc=a("6");Vc=a("");Wc=a("");Xc=a("7");Yc=a("");Zc=a("");$c=a("8");ad=a("");
bd=a("");cd=a("");dd=a("9");ed=a("");fd=a("10");gd=a("");hd=a("11");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");od=a("12");pd=a("");qd=a("");
rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("13");Ad=a("");Bd=a("");Ua=a("14");Cd=a("");Dd=a("30");Ed=a("31");Fd=a("");Gd=a("");
Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("15");Va=a("16");Nd=a("17");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("18");Yd=a("");Zd=a("");
$d=a("");ae=a("");be=a("");ce=a("19");de=a("");ee=a("");fe=a("");ge=a("");he=a("20");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");
te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");
Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("");$e=a("22");af=
a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("");of=a("");pf=a("");qf=a("");rf=a("");
sf=a("");tf=a("");uf=a("");vf=a("");wf=a("");xf="";yf=a("");zf=a("");Af=a("");Bf=a("");Cf=a("");Df=a("23");Ef=a("");Ff=a("");Gf=a("");Hf=a("");If=a("");Jf=
a("24");Kf=a("");Lf=a("");Mf=a("");Nf=a("")})();var Hb=function(a,b){Da(a,b)},yb=function(){},sa=function(a){return"function"==typeof a},Wa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Of=function(a){return"number"==Kb(a)&&!isNaN(a)},Pf=function(a){return/^[0-9]+$/.test(a)},lb=function(a){return"string"==Kb(a)},Qf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},va=function(a){return a?a.replace(/^\s+|\s+$/g,""):
""},W=function(a){return Math.round(Number(a))||0},Ha=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Rf=function(a){var b=[];if(Wa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},K=function(){return new Date},Aa=function(a,b){if(!Of(a)||!Of(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Sf=function(){this.prefix="gtm.";this.values={}};Sf.prototype.set=function(a,b){this.values[this.prefix+a]=b};
Sf.prototype.get=function(a){return this.values[this.prefix+a]};Sf.prototype.contains=function(a){return void 0!==this.get(a)};
var Tf=function(a,b,c){try{if(!a[be])return a[Ua](a,b||yb,c||yb);c&&c()}catch(d){}return!1},Uf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=va(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Vf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Wf=function(a){var b=Ba.f;return function(){return a(b)}},Xf=function(a){for(var b=0;b<a.length;b++)a[b]()},Ea=function(){return"gtm"+bg()},
bg=function(){var a=ob.sequence||0;ob.sequence=a+1;return a},Ga=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},cg=function(a){return null!==a&&void 0!==a&&void 0!==a.length},dg=function(a,b){0==b?a.Pb=!0:a.ja=!0;var c=a.i;a.C&&(a.C.lb[c]=b);Pb[c]&&(Pb[c].state=b)},eg=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},fg=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var B=window,P=document,hg=navigator,Qa=function(a,b){var c=B[a];B[a]=void 0===c?b:c;return B[a]},ka=function(a,b,c,d){return(d||"http:"!=B.location.protocol?a:b)+c},ig=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},sb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},u=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;sb(d,b);c&&(d.onerror=c);ig(d);return d},pa=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";ig(c);sb(c,b);void 0!==a&&(c.src=a);return c},J=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},R=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},na=function(a,b,c){a.removeEventListener?
a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},w=function(a){B.setTimeout(a,0)},ub=!1,vb=[],jg=function(a){if(!ub){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ub=!0;for(var e=0;e<vb.length;e++)w(vb[e])}vb.push=function(){for(var a=0;a<arguments.length;a++)w(arguments[a]);return 0}}},kg=0,lg=function(){if(!ub&&140>kg){kg++;try{P.documentElement.doScroll("left"),jg()}catch(a){B.setTimeout(lg,50)}}},
fa=function(a){var b=P.getElementById(a);if(b&&ta(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ta(document.all[a][c],"id")==a)return document.all[a][c];return b},ta=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},hb=function(a){return a.target||a.srcElement||{}},ua=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Bb=function(a){var b=P.createElement("div");
b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},ib=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;var e=a;for(d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},mg=!1,ng=[],og=function(){if(!mg){mg=!0;for(var a=0;a<ng.length;a++)w(ng[a])}},pg=function(a){a=a||B;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},zb=function(a){window.console&&
window.console.log&&window.console.log(a)};var qg=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},U=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||B.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||B.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=
f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:B.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Qf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=qg(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},ya=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,
c)}return b},xa=function(a){var b=P.createElement("a");a&&(b.href=a);return b};var oa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var mb=function(a){return encodeURIComponent(a)},da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=U(xa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var S=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},qb=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c},Ca=function(a,b){Da(a,b)},Ia=function(a){return W(a)},Cb=function(a,b){return Qf(a,b)};var rg={event:function(a){var b=a[1];if(lb(b)&&!(3<a.length)){var c;if(2<a.length){if(!Fa(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=Da(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&Fa(a[1])?b=Da(a[1],void 0):3==a.length&&lb(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var sg=new Sf,tg={},vg={set:function(a,b){Da(ug(a,b),tg)},get:function(a){return Y(a,2)},reset:function(){sg=new Sf;tg={}}},Y=function(a,b){var c;if(2!=b)c=sg.get(a);else a:{for(var d=a.split("."),e=0,f=tg.eventModel;void 0!==f&&e<d.length;e++)f=f[d[e]];if(void 0!==f||1<e)c=f;else{var g=tg;for(e=0;e<d.length;e++){if(void 0===g[d[e]]){c=void 0;break a}g=g[d[e]]}c=g}}return c},wg=function(a,b){sg.set(a,b);Da(ug(a,b),tg)},ug=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]=
{};d[e[e.length-1]]=b;return c};var xg=!1,yg=!1;var zg=Math.random(),Ag="0.050000">zg;
var Bg=function(a,b){if(Ag){var c=Ob,d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",K().getTime()-W(Nb));c+="&sr=0.050000";d("&ps=",zg);d("&cb=",Aa());J(c)}},Cg=yb,Dg=function(){var a=!1;
};var Fg=function(a){var b=ob.zones;return b?b.checkState(Ba.f,a):Eg},Eg={active:!0,isWhitelisted:function(){return!0}};var Hg=yb,Ig=[],Jg=!1,ma=function(a){return B["gtmDataLayer"].push(a)},Kg=function(a){var b=!1;return function(){!b&&sa(a)&&w(Wf(a));b=!0}},Tg=function(){for(var a=!1;!Jg&&0<Ig.length;){Jg=!0;delete tg.eventModel;var b=Ig.shift();if(sa(b))try{b.call(vg)}catch(Ja){}else if(Wa(b))a:{var c=b;if(lb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=tg,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Ja){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&lb(l[0])){var m=rg[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){Jg=!1;continue}}var n=void 0,p=void 0,t=b,v=t._clear;for(p in t)t.hasOwnProperty(p)&&"_clear"!==p&&(v&&wg(p,void 0),wg(p,t[p]));var r=!1,x=t.event;if(x){t.hasOwnProperty("gtm.uniqueEventId")||(t["gtm.uniqueEventId"]=bg(),wg("gtm.uniqueEventId",t["gtm.uniqueEventId"]));n=t["gtm.uniqueEventId"];wa=x;var E=Fg(n);if(E.active){var F=Kg(t.eventCallback),y=t.eventTimeout;
y&&B.setTimeout(F,Number(y));r=Hg(n,x,E.isWhitelisted,F,t.eventReporter)}}Nb||(Nb=t["gtm.start"])&&Cg();var I,N=t,C=n,A=x,D=tg;wa=null;a=r||a}Jg=!1}return!a},Ug=function(){var a=Tg();try{var b=B["gtmDataLayer"].hide;if(b&&void 0!==b[Ba.f]&&b.end){b[Ba.f]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},Vg=function(){var a=Qa("gtmDataLayer",[]),b=Qa("google_tag_manager",{});b=b["gtmDataLayer"]=b["gtmDataLayer"]||{};vb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});ng.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Ig.push.apply(Ig,b);300<this.length;)this.shift();return Tg()};Ig.push.apply(Ig,a.slice(0));w(Ug)};var Za,Wg,Xg,eb=/(Firefox\D28\D)/g.test(hg.userAgent),Zg=function(a,b){return function(c){c=c||B.event;var d=hb(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=ib(d,["a","area"]),e=!d||!d.href||Yg(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Za:Xg;if(c.defaultPrevented||!1===c.returnValue||c.na&&c.na()){if(d){var g={simulateDefault:!1},h=$a(f,["wnc","nwnc"]);h&&ab(a,d,g,f.wt,h)}}else{if(d){g={};var k,l=$a(f,
["wnc","nwnc","nwc","wc"]);(k=ab(a,d,g,f.wt,l))||(bb(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&eb;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=fb(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},ab=function(a,b,c,d,e){var f=d||2E3,g=Db(b,a);switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g.eventTimeout=f;g.eventCallback=$g(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=
e||"";g.event="gtm.formSubmit";g.eventTimeout=f;g.eventCallback=ah(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";break;default:return!0}return ma(g)},db=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},fb=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(hg.userAgent),e=db(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);
b.targetWindow=B.frames&&B.frames[f]||B[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+K().getTime(),b.targetWindow=B.open("",b.targetWindowName));break;default:d&&!B.frames[e]?(b.simulateDefault=!1,c=!0):(B.frames[e]||(b.targetWindowName=e),b.targetWindow=B.frames[e]||B.open("",e))}return c},$g=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||K().getTime(),500>K().getTime()-c&&B.setTimeout($g(a,
b,c),25)))}},ah=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;cb(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||K().getTime(),500>K().getTime()-c&&B.setTimeout(ah(a,b,c),25)}},$a=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},bh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;
f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},bb=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;for(var c=0;c<ch.length;c++)if(a.passingRules[c]){var d=dh[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=ch[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},za=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=hb(a);b&&
ab("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Wg&&(Wg=ya(P.location));bh(Xg,b||!1,c||!1,d,e);if(P.gtmHasLinkClickListenerTag)return;P.gtmHasLinkClickListenerTag=!0;f="click";g=Zg(a,b||!1);break;case "FORM_SUBMIT":bh(Za,b||!1,c||!1,d,e);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";g=Zg(a,b||!1);break;default:return}R(P,f,g,h)},Yg=function(a){if(!Wg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=xa(a);return Wg==ya(c)},cb=function(a){try{if(a.constructor&&
a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit},Db=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||ta(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};switch(b){case "LINK_CLICK":c["gtm.elementUrl"]=
a.href;break;case "FORM_SUBMIT":var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d;break;default:c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||""}return c},eh=function(){var a=function(a){var b=Qa("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Xg=a("linkClickMap");Za=a("formSubmitMap")};var fh=/(^|\.)doubleclick\.net$/i,gh=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,ra=function(a,b){for(var c=String(b||P.cookie).split(";"),d=[],e=0;e<c.length;e++){var f=c[e].split("="),g=va(f[0]);if(g&&g==a){var h=va(f.slice(1).join("="));h&&(h=decodeURIComponent(h));d.push(h)}}return d},ih=function(a,b,c,d,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";c&&(g+="path="+c+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==d?hh():[d||"none"];for(var k=0;k<h.length;k++){var l=g,m=h[k],
n=c;if(fh.test(B.location.hostname)||"/"==n&&gh.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=P.cookie;P.cookie=l;if(p!=P.cookie||0<=Qf(ra(a),b))return!0}return!1},jh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},kh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},hh=function(){var a=U(B.location,"host",!0).split(".");
if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var ea=function(a){var b=P;return lh?b.querySelectorAll(a):null},mh=!1;if(P.querySelectorAll)try{var nh=P.querySelectorAll(":root");nh&&1==nh.length&&nh[0]==P.documentElement&&(mh=!0)}catch(a){}var lh=mh;var oh=/^[a-zA-Z0-9_]+$/,ph=/^[a-zA-Z0-9-_]+$/;function qh(a){return a&&"string"==typeof a&&a.match(oh)?a:"_gcl"};var rh,sh;var Bh=function(){};var Jh;a:{Jh="G"}var Kh={"":"n",UA:"u",AW:"a",DC:"d",GTM:Jh},Lh="www.googletagmanager.com/gtm.js";
var Mh=Lh,gb=function(a,b,c){R(a,b,c,void 0)},ba=function(a,b,c){u(a,b,c)},Ya={},Ka=function(a,b,c){var d=Ya[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.Qb:a.Cb,d=0;d<c.length;d++)B.setTimeout(c[d],0)}};d={status:1,Qb:[],Cb:[],Yc:void 0};d.Ed=u(a,e(d,2),e(d,3));Ya[a]=d}0===d.status&&(d.Yc(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.Qb.push(b),c&&d.Cb.push(c))},ca=function(){return B.location.href},T=function(a,b){return Y(a,b||
2)},aa=function(a,b){B[a]=b},q=function(a,b,c){var d=B;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},Ta=function(a,b,c){var d=b,e=c,f;a:{if(a){if("string"==typeof a){var g=qh(a);f={Va:g,Ua:g};break a}if(a&&"object"==typeof a){f={Va:qh(a.dc),Ua:qh(a.aw)};break a}}f={Va:"_gcl",Ua:"_gcl"}}var h=f;e=e||"auto";d=d||"/";var k=xa(B.location.href),l=U(k,"query",!1,void 0,"gclid"),m=U(k,"query",!1,void 0,"gclsrc");if(!l||!m){var n=U(k,"fragment");l=l||qg(n,"gclid");m=m||qg(n,"gclsrc")}if(void 0!==l&&
l.match(ph)){var p=(new Date).getTime(),t=new Date(p+7776E6),v=["GCL",Math.round(p/1E3),l].join(".");m&&"aw.ds"!=m||ih(h.Ua+"_aw",v,d,e,t,!0);"aw.ds"!=m&&"ds"!=m||ih(h.Va+"_dc",v,d,e,t,!0)}},z=function(a,b,c,d){var e=!d&&"http:"==B.location.protocol;e&&(e=2!==nb());return(e?b:a)+c},ia=function(a){var b=0;return b},Eb=function(a){},ja=function(a){var b=!1;return b},Pa=function(a,b,c){},Gb=void 0,Oa=function(a){if(!Gb){var b=function(){var a=P.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<
Gb.length;a++)w(Gb[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;gb(a,"DOMNodeInserted",function(){b||(b=!0,w(function(){b=!1;for(var a=0;a<Gb.length;a++)w(Gb[a])}))})}};Gb=[];P.body?b():w(b)}Gb.push(a)},qa=function(a){var b=Ba.f.split("-"),c=b[0].toUpperCase(),d=Kh[c];d||(d="i");var e="";a&&"GTM"==c&&(e=b[1]);return d+"ag"+e},nb=function(){var a=Mh;a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=P.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=
e[f].src;if(g){g=g.toLowerCase();if(eg(g,c))return 3;1===d&&eg(g,b)&&(d=2)}}return d};var Nh=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Oh={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Ph={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Qh=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Mg=function(a){var b=Y("gtm.whitelist");
var c=b&&Qh(Rf(b),Oh),d=Y("gtm.blacklist")||Y("tagTypeBlacklist")||[];Nh.test(B.location&&B.location.hostname)&&(d=Rf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&Qh(Rf(d),Ph),f={};return function(g){var h=g&&g[Ua];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Qf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
Qf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=Qf(e,h.a)))a:{for(var t=h.b||[],v=new Sf,r=0;r<e.length;r++)v.set(e[r],!0);for(r=0;r<t.length;r++)if(v.get(t[r])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var _c=function(a){return a[Jf]};_c.a="c";_c.b=["google"];var _ctv=function(){return"5"};_ctv.a="ctv";_ctv.b=["google"];var _eu=function(a){var b=String(Y("gtm.elementUrl")||a[$c]||""),c=xa(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return wa};_e.a="e";_e.b=["google"];var Vh=function(a,b){this.h=a;this.o=b};Vh.prototype.toString=function(){var a=""+this.h;1<this.o&&(a=a+"-"+this.o);return a};var Wh=function(a,b){this.jb=a;this.Da=b};Wh.prototype.toString=function(){return""+this.Da+"."+this.jb};var Zh=function(a,b){var c=new Xh(null,a,b);Yh(c);return c},Xh=function(a,b,c){this.yb=Math.floor(K().getTime()/864E5);this.Ba=b||"auto";this.qa=c||"/";var d=jh(this.Ba),e=kh(this.qa);this.J=a||new Vh(d,e);this.j=[];this.F=new Sf},ai=function(a,b,c){b&&(""==c.jb?$h(a,b):(a.F.contains(b)||a.j.push(b),a.F.set(b,c)))},bi=function(a,b){for(var c=0;c<b.length;c++)ai(a,b[c][0],b[c][1])},$h=function(a,b){var c=Qf(a.j,b);0<=c&&a.j.splice(c,1);a.F.set(b,void 0)},ci=function(a){for(var b=[],c=0;c<a.j.length;c++){var d=
a.j[c];b.push([d,a.F.get(d)])}return b},di=function(a){for(var b=0,c=0;c<a.j.length;c++)b=Math.max(b,a.F.get(a.j[c]).Da);return 864E5*b};Xh.prototype.toString=function(){if(0==this.j.length)return"";for(var a=[],b=0;b<this.j.length;b++){var c=this.j[b];a.push(""+c+"."+this.F.get(c).toString())}return"GAX1."+this.J.toString()+"."+a.join("!")};
var ei=function(a,b){for(var c=new Date,d=kh(a.qa),e=[],f=0;f<a.j.length;f++){var g=a.j[f];a.F.get(g).Da<a.yb&&e.push(g)}for(f=0;f<e.length;f++)$h(a,e[f]);if(a.j.length>(b||10))return!1;c.setTime(di(a));if("auto"!=a.Ba)return ih("_gaexp",a.toString(),a.qa,a.Ba,c);for(var h=hh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.J=new Vh(jh(h[k]),d),ih("_gaexp",a.toString(),a.qa,h[k],c)))return!0;return!1},Yh=function(a){for(var b=a.J.h,c=a.J.o,d=ra("_gaexp"),e=[],f=0;f<d.length;f++){var g=fi(a,d[f]);g&&e.push(g)}fg(e,
function(a,d){var e=a.J,f=d.J;return e.h==f.h&&e.o==f.o?!1:e.h==b&&e.o==c?!0:f.h==b&&f.o==c?!1:e.h==b?f.h!=b||e.o<f.o:f.h==b?!1:e.o==c?f.h!=b&&(f.o!=c||e.h<f.h):f.o==c?!1:e.h<f.h||e.h==f.h&&e.o<f.o});a.J=0<e.length?e[0].J:new Vh(b,c);for(f=e.length-1;0<=f;f--)bi(a,ci(e[f]))},fi=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=va(e[0]);if(0!=f.length){var g=2==e.length?va(e[1]):"1";if(Pf(f)&&Pf(g)){d=new Vh(W(f),W(g));
break a}}}d=void 0}if(d){for(var h=new Xh(d,a.Ba,a.qa),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Pf(m[1]))return;ai(h,m[0],new Wh(m[2],W(m[1])))}}return h}}};var _v=function(a){var b=Y(a[he].replace(/\\\./g,"."),a[Sc]);return void 0!==b?b:a[$c]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(Y("gtm.referrer")||P.referrer);if(!b)return b;var c=xa(b);return b};_f.a="f";_f.b=["google"];var _smm=function(a){var b=a[Md],c=a[ce]||{};return c.hasOwnProperty(b)?c[b]:a[$c]};_smm.a="smm";_smm.b=["google"];var ji=function(a){var b=B.location,c;(c=a[Pc]?a[Pc]:Y("gtm.url"))&&(b=xa(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Ac]&&(f=U(b,a[Ac],a[Ue],a[Zc],a[He]));return f},_u=ji;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[bc]).indexOf(String(a[cc]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[bc])==String(a[cc])};_eq.a="eq";_eq.b=["google"];var jb=new String("undefined"),wb=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===jb?b:a[d]);return c.join("")}};wb.prototype.toString=function(){return this.resolve("undefined")};wb.prototype.valueOf=wb.prototype.toString;var ti={},xb=function(a,b){var c=bg();ti[c]=[a,b];return c},ui=function(a){var b=a?0:1;return function(a){var c=ti[a];if(c&&sa(c[b]))c[b]();ti[a]=void 0}};var vi=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},wi=function(a,b){return a<b?-1:a>b?1:0};var xi;a:{var yi=Ib.navigator;if(yi){var zi=yi.userAgent;if(zi){xi=zi;break a}}xi=""}var Z=function(a){return-1!=xi.indexOf(a)};var Ai=function(){return Z("iPhone")&&!Z("iPod")&&!Z("iPad")};var Bi=function(a){Bi[" "](a);return a};Bi[" "]=function(){};var Di=function(a,b){var c=Ci;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ei=Z("Opera"),Fi=Z("Trident")||Z("MSIE"),Gi=Z("Edge"),Hi;if(Hi=Z("Gecko")){var Ii;Ii=-1!=xi.toLowerCase().indexOf("webkit");Hi=!(Ii&&!Z("Edge"))}var Ji=Hi&&!(Z("Trident")||Z("MSIE"))&&!Z("Edge"),Ki,Li=(Ki=-1!=xi.toLowerCase().indexOf("webkit"))&&!Z("Edge");Li&&Z("Mobile");Z("Macintosh");Z("Windows");Z("Linux")||Z("CrOS");var Mi=Ib.navigator||null;Mi&&(Mi.appVersion||"").indexOf("X11");Z("Android");Ai();Z("iPad");Z("iPod");Ai()||Z("iPad")||Z("iPod");
var Ni=function(){var a=Ib.document;return a?a.documentMode:void 0},Oi;a:{var Pi="",Qi=function(){var a=xi;if(Ji)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Gi)return/Edge\/([\d\.]+)/.exec(a);if(Fi)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Li)return/WebKit\/(\S+)/.exec(a);if(Ei)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Qi&&(Pi=Qi?Qi[1]:"");if(Fi){var Ri=Ni();if(null!=Ri&&Ri>parseFloat(Pi)){Oi=String(Ri);break a}}Oi=Pi}
var Si=Oi,Ci={},Ti=function(a){return Di(a,function(){for(var b=0,c=vi(String(Si)).split("."),d=vi(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=wi(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||wi(0==k[2].length,0==l[2].length)||wi(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Ui;
var Vi=Ib.document;Ui=Vi&&Fi?Ni()||("CSS1Compat"==Vi.compatMode?parseInt(Si,10):5):void 0;var Wi;if(!(Wi=!Ji&&!Fi)){var Xi;if(Xi=Fi)Xi=9<=Number(Ui);Wi=Xi}Wi||Ji&&Ti("1.9.1");Fi&&Ti("9");var Ab=function(a,b){var c="";Fi&&!Yi(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Zi)a.srcdoc=d;else if($i){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else aj(a,d)},Zi=Li&&"srcdoc"in document.createElement("iframe"),$i=Ji||Li||Fi&&Ti(11),aj=function(a,b){Fi&&Ti(7)&&!Ti(10)&&6>bj()&&cj(b)&&(b=dj(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Fi&&!Yi(a)?ej(a,c):c()},bj=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Yi=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Bi(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},fj=0,ej=function(a,b){var c="goog_rendering_callback"+fj++;Ib[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},cj=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},dj=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var vj=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=sj(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=tj(f,g);uj(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},wj=null,sj=function(a){if(wj)return wj;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return wj=
c}0==a.styleSheets.length&&a.createStyleSheet();return wj=a.styleSheets[0]},tj=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},uj=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Dj={},Ej=void 0,Fj=function(a){var b=Dj[a];b||(b={id:a,w:[],ma:0,nb:null,Za:void 0,eb:!1},Dj[a]=b);Ej=b},Hj=function(a,b,c,d){var e=Ej;if(!lh||!e)return!1;var f={id:e.id+":"+e.w.length,ac:b,ea:[],Wb:c,K:a,Ta:0,Ja:d||null,xb:0,la:!1};e.w.push(f);null===a?(f.la=!0,b(null)):Gj(e);return!0},Ij=function(a){var b=vj(a,"visibility","hidden",!0);return function(){sa(b)&&b.apply();b=null}},Jj=function(a,b,c,d){var e=b;if(!ub){var f=Ij(a.B);vb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Hj(a,
e,c,d)},Gj=function(a){if(!a.eb){for(var b=a.ma;b<a.w.length;b++){var c=a.w[b],d=b==a.ma;if(!c.la&&!Kj(d,c))break;c.la&&d&&a.ma++}a.w.length>a.ma?(a.nb||(a.nb=B.setTimeout(function(){a.nb=null;Gj(a)},80)),ub||a.Za||(a.Za=function(){w(function(){Gj(a)})},R(P,"DOMContentLoaded",a.Za))):Lj(a)}},Lj=function(a){for(var b=0;b<a.w.length;b++){var c=a.w[b];if(c.K)for(var d=ea(c.K.B)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Mj(f,c.id),c.ea.push(Nj(f,c.id)))}}},
Kj=function(a,b){var c=[];if(b.K){var d=Oj(b.K,b.id),e=null;b.Ja&&(e=Oj(b.Ja,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ub&&(null===b.Ja.u||b.xb+c.length<b.Ja.u)))break;c.push({element:g,ad:h})}}if(!ub&&b.Wb&&(!a||null==b.K.u||b.K.u!=b.Ta+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].ad,n;b.Ta++;Mj(l,b.id);m&&(b.xb++,n=b.id+"-t",Mj(m,n));var p=b.ac(l,m);sa(p)&&b.ea.push(p);b.ea.push(Nj(l,b.id));m&&n&&b.ea.push(Nj(m,n))}if(b.K.u&&
b.K.u==b.Ta||ub)b.la=!0;return!0},Mj=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Nj=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Oj=function(a,b){for(var c=ea(a.B)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.I&&!Pj(f))break;d.push(f)}}return d},Pj=function(a){if(ub)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Na=function(a,b){var c=b||Ib,d=c.onerror,e=!1;Li&&!Ti("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,line:h,lineNumber:h,ud:k,error:l});return e}};var lk=function(a){if(!a)return!1;if(a[ac]&&Wa(a[cc])){for(var b=a[cc],c=0;c<b.length;c++)if(a[cc]=b[c],Tf(a))return!0;return!1}return Tf(a)};var Hk=92,Ik=[],Jk=[],Ng=[],Kk=new Sf,Lk=[],Mk=[],ch=[],dh=[],Nk=function(){this.S=[]};Nk.prototype.set=function(a,b){this.S.push([a,b]);return this};Nk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.S.length;d++){var e=Qg(this.S[d][0],a,b),f=Qg(this.S[d][1],a,b);c[e]=f}return c};var Ok=function(a){this.index=a};Ok.prototype.resolve=function(a,b){var c=Ng[this.index];if(c&&!b(c)){var d=c[Va];if(a){if(a.get(d))return;a.set(d,!0)}c=Qg(c,a,b);a&&a.set(d,!1);return Tf(c)}};
var _M=function(a){return new Ok(a)},Pk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Qg(Ik[a[f]],b,c);g===jb&&(e=!0);d.push(g)}return e?new wb(d):d.join("")}},_T=function(a){return new Pk(arguments)},Qk=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Qg(a[0],c,d);if(a[0]instanceof Ok&&b(8)&&b(16)){if(e===jb)return e;var f=Ea();Kk.set(f,e);return'google_tag_manager["'+Ba.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=mk[a[g]](e);return e}},_E=function(a,b){return new Qk(arguments)},Rk=function(a,b){this.A=a;this.ua=b},_R=function(a,b){return new Rk(a,b)};
var Qg=function(a,b,c){var d=a;if(a instanceof Ok||a instanceof Nk||a instanceof Pk||a instanceof Qk)return a.resolve(b,c);if(!(a instanceof Rk))if(Wa(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Qg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Qg(a[f],b,c))}return d},Uk=function(){for(var a=[_eq,_e,'_event',_M(0),'concordEvent','2038726_4',_ua,true,__c,'property id - console','1','UA-36037335-1',_M(1),false,'14','19','20','15','17','16','31','Container ID and Version',_c,'Container ID','GTM-MVMGKF',_M(2),':',_ctv,'Container Version',_M(3),_T(25,26,29),_M(4),_v,'eventType',2,_M(5),'eventName',_M(6),'pageName',_M(7),'signedIn',_M(8),_smm,'internalUser Lookup','internalUser',_M(9),'true','True',{10:47,46:47,47:47},'',_M(10),'projectNumber','not set',_M(11),{14:31,15:35,16:37,17:39,18:41,19:50,20:53},'allowLinker','anonymizeIp','cookieDomain','legacyHistoryImport','page','title','false','auto','/virtual/','/',_T(63,35,64,37),'packageName\x3d','packageName',_M(12),'\x26','metadata',_M(13),_T(66,68,69,71),{55:46,56:61,57:62,58:61,59:65,60:72},'\x26tid','\x26cd14','\x26cd19','\x26cd20','\x26cd15','\x26cd17','\x26cd16','\x26cd31',{74:12,75:31,76:35,77:37,78:39,79:41,80:50,81:53,55:46,56:61,57:62,58:61,59:65,60:72},1,'connectApp','finish',_cn,'packageType\x3dios','2038726_5',__awct,'978586856','gUraCIH9hWcQ6JnQ0gM',_u,'_url',_M(14),'packageType\x3dandroid','2038726_6','mlEtCJOFgWcQ6JnQ0gM',3,'trackExperiment','2038726_8','configureExperiment','experimentID','experimentType',_M(15),'exp name goes here','exp id goes here',{105:106},_M(16),{14:31,15:101,16:108,17:39,18:41,19:50,20:53},'/virtual/configureExperiment/',_T(110,104),'expId\x3d',',expVar\x3d','experimentVariant','variant',_M(17),_T(112,108,113,116),{55:46,56:61,57:62,58:61,59:111,60:117},{74:12,75:31,76:101,77:108,78:39,79:41,80:50,81:53,55:46,56:61,57:62,58:61,59:111,60:117},4,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=
Tk(c,a);return b},Tk=function(a,b){var c=b[a],d=c;if(c instanceof Ok||c instanceof Qk||c instanceof Pk||c instanceof Rk)d=c;else if(Wa(c)){d=[];for(var e=0;e<c.length;e++)d[e]=Tk(c[e],b)}else if("object"==typeof c){d=new Nk;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],Tk(c[f],b))}return d},Wk=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Ik[e[1]]);if(1==a){var f=Vk(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=Jk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=Vk(e[g]);3==a&&(c[d]=Ik[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Ik[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Vk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Hk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Xk=function(a,b,c){a.push.apply(a,Wk(b,c))};var Yk;
var Pg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=al[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},dl=function(a){},el=function(a,b){},Sg=function(a){};var fl,gl;var rl=function(a){return function(){}},sl=function(a){return function(){}};var tl=function(a){var b=this;this.i=a;this.ja=this.Pb=!1;this.Ia=[];this.Ea=[];this.ba=function(){b.ja||Xf(b.Ia);dg(b,1);if(Qb[a])for(var c=0;c<Qb[a].length;c++)Qb[a].shift().ba()};this.aa=function(){b.ja||Xf(b.Ea);dg(b,2);if(Qb[a])for(var c=0;c<Qb[a].length;c++)Qb[a].shift().aa()};this.D=yb},ul=function(a,b){a.Ia.push(b)},vl=function(a,b){a.Ea.push(b)},wl=function(a){this.M=[];this.kb=[];this.Ab={};this.Hb=[];this.Z=0;this.ib={};this.mb={};this.lb={};this.event=a};wl.prototype.addListener=function(a){this.Hb.push(a)};
var xl=function(a){0<a.Z||Xf(a.Hb)},yl=function(a,b,c,d,e,f){if(!c.ja){a.M[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=Wa(d)?d.slice():["or",d];e=Wa(e)?e.slice():[e];f=Wa(f)?f.slice():[f];a.Ab[b]=d;a.ib[b]=0<e.length;a.mb[b]=0<f.length;a.Z++;var g=function(){0<a.Z&&!a.ib[b]&&!a.mb[b]&&a.Z--;xl(a)};ul(c,g);vl(c,g)}},Dl=function(a){for(var b=[],c={},d=0;d<a.M.length;c={U:c.U},d++)if(c.U=a.M[d],c.U){var e=a.Ab[d],f=a.ib[d],g=a.mb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=zl(e,
c.U.D),k=0;k<e.length;k++)e[k]instanceof Rk&&e[k].A!=d&&Al(a,e[k].A,h);(f||g)&&Bl(a,d,function(a){return function(){0<a.U.C.Z&&a.U.C.Z--;xl(a.U.C)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.M[b[d]].D();for(d=0;d<a.kb.length;d++){var l=a.kb[d];Cl(l);0<l.length&&l[0].D()}},Al=function(a,b,c){a.M[b]&&(ul(a.M[b],function(){c(b,!0)}),vl(a.M[b],function(){c(b,!1)}))},zl=function(a,b){var c=yb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof Rk&&a[h].A===e||a[h]===e){g=
h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Bl=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Mk[b];if(a.event.g(h)){}else g=El(h,b,a.event.g,a);if(c=g){var k=Fl(b,!0);0<k.length&&f(k[0].A);d.push(c);var l=Fl(b,!1);0<l.length&&f(l[0].A)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Fl(h.i,!0);if(0<k.length){var l=d[g-1],m=Gl(h);ul(l,m);0==k[0].ua?vl(l,m):vl(l,c)}var n=Fl(h.i,!1);0<n.length&&(m=Gl(d[g+1]),ul(h,m),0==n[0].ua?vl(h,m):vl(h,c))}ul(d[d.length-1],c);vl(d[d.length-1],c);a.kb.push(d)}},Fl=function(a,b){var c=b?Re:hf,d=Mk[a],e=void 0===d[c]?[]:d[c];return Wa(e)?e:[e]},Gl=function(a){return function(){a.D()}},Cl=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=Pb[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.C.lb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=Fl(a[c+1].i,!0);if(0<h.length&&1==h[0].ua)for(++c;c<a.length;c++)b.push(a[c])}}var k=Hl(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],t=p[0],v=p[p.length-1],r,x=0;x<a.length;x++){var E=a[x];!m&&E.i==t&&0<x&&(m=a[x-1]);E.i==v&&x<a.length-1&&(n=a[x+1]);if(-1<Qf(p,E.i))if(r=a.splice(x,1)[0],E.i==v)break;else x--}if(r){var F=Number(l),y=m,I=n;if(y){var N=y.Ia[0],C=y.Ea[0],A=y;A.Ia=[];A.Ea=
[];ul(y,N);vl(y,C)}if(y&&I){var D=Gl(I);ul(y,D);var G=Fl(y.i,!1);0<G.length&&G[0].A!=F&&0==G[0].ua&&vl(y,D);var L=Fl(I.i,!0);0<L.length&&L[0].A!=F&&0==L[0].ua&&vl(y,D)}}}},Hl=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Fl(a,!0);0<b.length&&f(b[0].A);e.push(a);var c=Fl(a,!1);0<c.length&&f(c[0].A)};f(d.i);b[d.i]=e}Il(a,b);return b},Il=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Qf(b[e],d)){delete b[d];break}}};var Jl=function(a,b,c){return function(){a[Dd]=b.ba;a[Ed]=b.aa;var d=b.i,e=b.C&&b.C.lb[d],f=Pb[d]&&Pb[d].state,g=e?void 0!==e:b.Pb||b.ja,h=Pb[d]&&Pb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){dg(b,0);var m=b.C?b.C.event:void 0,n=a;n=Qg(n,new Sf,c);a=n;if(m){}Tf(a,b.ba,b.aa)}else k&&0==f||l&&0==e?Qb[d].push(b):k&&1==f||l&&1==e?b.ba():b.aa()}},El=function(a,b,c,d){var e=d&&d.M,f;if(f=e)a:{if(e&&Wa(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].i===b){f=e[g];break a}f=void 0}var h=f||new tl(b);h.C=d;ul(h,rl(a));vl(h,sl(a));h.D=Jl(a,h,c);return h};
var Nl=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];B[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!Fa(b))return!1;for(var e=Ga(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[hd]?c=Y("ecommerce"):
a[gd]&&(c=a[gd].ecommerce);if(!Fa(c))return;c=Object(c);var e=Ga(a[zd],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&v[e]||!c&&void 0===v[e])){var f=r[e]?Ha(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}Qa("GoogleAnalyticsObject",a[he]||"ga");var l=function(){return B.GoogleAnalyticsObject},m=Qa(l(),function(){var a=B[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(K());var n="",p="";"string"!=typeof a[vf]?(p=Ea(),n=p+"."):""!==
a[vf]&&(p=a[vf],n=p+".");var t=!1;var v={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0},r={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useBeacon:!0};
var x={name:p};k(a[zd],x,!0);m("create",a[Sb],x);d("set","&gtm",qa(!0));g("dimension",a[dd]);
var E={};k(a[zd],E,!1)&&d("set",E);var F;a[Xd]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(sa(a[Fd]))a[Fd]();else{var c=a[zd],d=c&&c.hitCallback;sa(d)&&d()}b()});if(a[rf]){}else if(a[sf]){}else if(a[uf]){}else if(a[tf]){}else if(a[Yc]){}else if(a[Wc]){}else if(a[qf]){}else{a[od]&&(d("require","ec","ec.js"),h());if(a[fd]&&!a[qd]){var L="_dc_gtm_"+String(a[Sb]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:L})}F?d("send","pageview",F):d("send","pageview");}if(!Nl){var Q=a[Uc]?"u/analytics_debug.js":"analytics.js";a[Nd]&&!a[Uc]&&(Q="internal/"+Q);Nl=
!0;u(ka("https:","http:","//www.google-analytics.com/"+Q,t),function(){B[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Ql=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Lk[b]&&Qg(Lk[b],new Sf,c),e=d;d&&(e=lk(d));a[b]=[e,d]}return a[b]}},Rl=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.Y(c[d],a.g)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.Y(e[d],a.g)[0])return!1;return!0},Sl=!1;
Hg=function(a,b,c,d,e){switch(b){case "gtm.js":if(Sl)return!1;Sl=!0;break;case "gtm.sync":if(Y("gtm.snippet")!=Mb)return!1}for(var f={id:a,name:b,za:d||yb,ia:Vk(),Ha:Vk(),Y:Ql(),g:Mg(c)},g=[],h=0;h<ch.length;h++)if(Rl(f,ch[h])){g[h]=!0;for(var k=f,l=ch[h],m=l[1],n=0;n<m.length;n++)k.ia[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Ha[p[n]]=!0}else g[h]=!1;var O=[];for(var M=0;M<Hk;M++)if(f.ia[M]&&!f.Ha[M])if(f.g(Mk[M])){}else{O[M]=
Mk[M];}f.ra=O;for(var ha=new wl(f),V=0;V<Hk;V++)if(f.ia[V]&&!f.Ha[V])if(f.g(Mk[V])){}else{var Ja=f.ra[V],Rj=El(Ja,V,f.g,ha);yl(ha,V,Rj,Ja[ad],Ja[Re],Ja[hf]);if(Ja[Rb])break}ha.addListener(f.za);Dl(ha);xl(ha);e&&sa(e)&&e({passingRules:g,resolvedTags:f.ra});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var $f in f.ra)if(f.ra.hasOwnProperty($f)){var ag=f.ra[$f];if(void 0==ag[Va]||!eg(ag[Va],"_implicit"))return!0}return!1};var Ul=function(){};var Vl=function(){};var Tl={macro:function(a){if(Kk.contains(a))return Kk.get(a)}};Tl.dataLayer=vg;Tl.onHtmlSuccess=ui(!0);Tl.onHtmlFailure=ui(!1);Tl.callback=function(a){Sa.hasOwnProperty(a)&&sa(Sa[a])&&Sa[a]();delete Sa[a]};
Tl.ic=function(){var a=B.google_tag_manager;a||(a=B.google_tag_manager={});ob=a;if(a[Ba.f]){var b=ob.zones;b&&b.registerNatural(Ba.f)}else{a[Ba.f]=Tl;Bh();eh();Ik.push.apply(Ik,Uk());Xk(Jk,0,"14:0,14:1,16:2,2:3,3:4,14:6,21:7,14:8,16:9,25:10,29:11,0:12,12:13,11:13,16:21,14:22,16:23,24:24,14:27,16:28,29:30,14:32,16:33,20:33,5:34,16:36,20:36,16:38,20:38,16:40,20:40,14:42,16:43,16:44,20:44,15:45,19:48,8:49,16:51,20:51,8:52,9:54,23:13,16:67,20:67,16:70,20:70,13:73,6:13,17:7,7:13,1:82,18:13,10:13,22:83,2:35,3:84,2:37,3:85,14:86,2:71,3:87,14:89,26:90,27:91,14:92,16:93,28:94,22:34,3:95,27:97,22:98,3:99,16:102,16:103,20:103,15:104,19:107,9:109,16:114,20:115,13:118,1:119,22:120,16:121,16:122,4:123,16:124,4:125,14:126,16:127,16:128");Xk(Ng,1,"G,Ae,AA4,AAAD,AKEE,AAA4B,AAAIH,AAAIZ,AAAIhB,AAAIBY,AAAAAmD,AAAIBAc,AAAIBAAG,AAAIBAAY,AAAAAAAAAAgB,AAAIBAAAAAAAM,AAAAACCAAAAAy,AAAIBAAAAAAAAG,AAAAAAAAAAgAAAB,AAAAAAAAAAgAAAG,AAAAAAAAAAgAAAY,AAAAAAAAAAAAAAgB,CAAAAAAAAAAAAAAC");Xk(Lk,1,"Z,BAAAAAAAAG,BAAAAAAAAY,AAAAAAAAAgD,AAAAAAAAAgBI,JAAAAAAAAAAAB");Xk(Mk,1,"ghDAAAgh_B,AJAAAAAAAAcG,AJAAAAAAAAMy,ghDAAAAB3AAAA5");Xk(ch,2,"B:B::,P:C::,X:E::,g:I::");Xk(dh,4,"5:,88:,96:,100:");for(var c=0;c<Mk.length;c++){var d=Mk[c],e=1;d[oe]?e=2:
d[Af]&&(e=0);Pb[c]={firingOption:e,state:void 0};Qb[c]=[]}Dg();Vg();var n=B;if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)jg();else{R(P,"DOMContentLoaded",jg);R(P,"readystatechange",jg);if(P.createEventObject&&P.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(E){}p&&lg()}R(n,"load",jg)}"complete"===P.readyState?og():R(B,"load",og);Vl();Ul();a:{}}};Tl.ic();var _vs="res_ts:1476382725537000,srv_cl:172292384,ds:live,cv:5";
})()
